# Generated by Django 4.2.13 on 2025-12-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                ("amount", models.IntegerField(blank=True, default=0)),
                ("point", models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
