# Generated by Django 4.2.13 on 2025-12-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="point",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
